package com.cognizant.academy.qbthon.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "inqevents")
public class Events {
	@DynamoDBHashKey(attributeName = "event_id")
    @DynamoDBAutoGeneratedKey
    private String eventId;

    @DynamoDBAttribute(attributeName = "event_name")
    private String eventName;

    @DynamoDBAttribute(attributeName = "date")
    private String date;

    @DynamoDBAttribute(attributeName = "slot")
    private String slot;
    
    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName = "skills")
    private List<Skill> skills;
    
    private String skillsList;
    
    private String associateList;
    
    private String smeList;
    
    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName = "associate_details")
    private List<AssociateDetail> associateDetails;
    
    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName = "sme_details")
    private List<AssociateDetail> smeDetails;
 
}
