package com.cognizant.academy.qbthon.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "inqusers")
public class Users {

	@DynamoDBHashKey(attributeName = "user_id")
    @DynamoDBAutoGeneratedKey
	private String userId;
	
	@DynamoDBAttribute(attributeName="associate_id")
	private String associateId;
	
	@DynamoDBAttribute(attributeName="first_name")
	private String firstName;
	
	@DynamoDBAttribute(attributeName="last_name")
	private String lastName;
	
	@DynamoDBAttribute(attributeName="email")
	private String email;
	
	@DynamoDBAttribute(attributeName="user_type")
	private String userType;
		
}
